Update patch set 1
Patch Set 1: Code-Review-1

This breaks the whole camera stack on zl0 for some reason...


Logcat is an infinite loop of:
07-11 15:45:48.682  1659  1659 D /vendor/bin/adsprpcd: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:1124: Error 57: apps_dev_init failed. domain 0, errno Operation not permitted
07-11 15:45:48.682  1659  1659 D /vendor/bin/adsprpcd: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:1207: Error 57: open dev -1 for domain 0 failed
07-11 15:45:48.683  1659  1659 D /vendor/bin/adsprpcd: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:1124: Error 57: apps_dev_init failed. domain 0, errno Operation not permitted
07-11 15:45:48.683  1659  1659 D /vendor/bin/adsprpcd: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:1207: Error 57: open dev -1 for domain 0 failed
07-11 15:45:48.683  1659  1659 D /vendor/bin/adsprpcd: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:651: Error 3b: remote handle invoke failed. domain 0, handle ffffffff, sc 0, pra 0x0
07-11 15:45:48.683  1659  1659 E /vendor/bin/adsprpcd: vendor/qcom/proprietary/adsprpc/src/adsprpcd.c:43:adsp daemon will restart after 25ms...

Patch-set: 1
Reviewer: Jan Engelmohr <12537@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Code-Review=-1