Update patch set 7
Patch Set 7:

I can't even remove WIP flag from my own commit... darn.

git push ssh://ThEMarD@review.lineageos.org:29418/LineageOS/android_device_leeco_msm8996-common a9a72160026cfc43f79ffa84c384e135b2e4876b:refs/for/lineage-15.1%ready
Counting objects: 29, done.
Delta compression using up to 6 threads.
Compressing objects: 100% (26/26), done.
Writing objects: 100% (29/29), 3.39 KiB | 0 bytes/s, done.
Total 29 (delta 16), reused 0 (delta 0)
remote: Resolving deltas: 100% (16/16)
remote: Processing changes: refs: 1, done    
remote: (W) No changes between prior commit 70b4fba and new commit e2d730e
remote: (I) 9c48c2b: no files changed, message updated, was rebased
To ssh://ThEMarD@review.lineageos.org:29418/LineageOS/android_device_leeco_msm8996-common
 ! [remote rejected] a9a72160026cfc43f79ffa84c384e135b2e4876b -> refs/for/lineage-15.1%ready (only change owner can modify Work-in-Progress)
error: failed to push some refs to 'ssh://ThEMarD@review.lineageos.org:29418/LineageOS/android_device_leeco_msm8996-comm

Patch-set: 7
Reviewer: Marc Bourgoin <18394@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>